#!/usr/bin/env bash
# Deploy AttestRWA contracts to public Base Sepolia (opt-in).
#
# Prerequisites (.env — never commit):
#   PROD_RPC_URL=https://sepolia.base.org
#   PROD_ATTESTER_ADDRESS=0x...
#   PROD_ATTESTER_PRIVATE_KEY=0x...
#   EAS_SCHEMA_UID_SETTLEMENT_APPROVAL=0x1f64ec96...
#
# Uses a fresh state file .public-testnet.state (not the Anvil dev state).

set -euo pipefail

export PATH="$HOME/.foundry/bin:$PATH"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

STATE_FILE="${ATTESTRWA_PUBLIC_STATE_FILE:-.public-testnet.state}"

if [ ! -f .env ]; then
  echo "[public-testnet] Missing .env — copy from .env.example and set PROD_* vars." >&2
  exit 1
fi

# shellcheck disable=SC1091
set -a
source .env
set +a

: "${PROD_RPC_URL:?Set PROD_RPC_URL in .env}"
: "${PROD_ATTESTER_ADDRESS:?Set PROD_ATTESTER_ADDRESS in .env}"
: "${PROD_ATTESTER_PRIVATE_KEY:?Set PROD_ATTESTER_PRIVATE_KEY in .env}"
: "${EAS_SCHEMA_UID_SETTLEMENT_APPROVAL:?Set EAS_SCHEMA_UID_SETTLEMENT_APPROVAL}"

log() { printf '[public-testnet] %s\n' "$*" >&2; }

log "Writing $STATE_FILE for Base Sepolia deploy…"

cat >"$STATE_FILE" <<EOF
# Generated by scripts/deploy-public-testnet.sh — do not commit secrets
DEV_RPC_URL=$PROD_RPC_URL
DEV_CHAIN_ID=84532
ATTESTER_ADDRESS=$PROD_ATTESTER_ADDRESS
ATTESTER_PRIVATE_KEY=$PROD_ATTESTER_PRIVATE_KEY
EAS_SCHEMA_UID_SETTLEMENT_APPROVAL=$EAS_SCHEMA_UID_SETTLEMENT_APPROVAL
EAS_ADDRESS=${EAS_ADDRESS:-0x4200000000000000000000000000000000000021}
EAS_SCHEMA_REGISTRY_ADDRESS=${EAS_SCHEMA_REGISTRY_ADDRESS:-0x4200000000000000000000000000000000000020}
EOF

log "Register schema on Base Sepolia if not already present (see docs/ATTESTATION_SCHEMA.md §2)."
log "Deploying MockUSDC + SettlementEscrow…"

ATTESTRWA_STATE_FILE="$STATE_FILE" ./scripts/deploy-contracts.sh

# shellcheck disable=SC1090
source "$STATE_FILE"

SCHEMA_UID="$EAS_SCHEMA_UID_SETTLEMENT_APPROVAL"
cat <<EOF

================================================================
Public Base Sepolia deploy complete
================================================================
  Escrow (BaseScan)   : https://sepolia.basescan.org/address/${SETTLEMENT_ESCROW_ADDRESS:-unknown}
  MockUSDC            : ${MOCK_USDC_ADDRESS:-unknown}
  Attester EOA        : $ATTESTER_ADDRESS
  Schema (EAS Scan)   : https://base-sepolia.easscan.org/schema/view/${SCHEMA_UID}
  Next                : ./scripts/public-attestation-smoke.sh
================================================================
EOF
